import type { NextPage } from 'next'
import Head from 'next/head'

import Basket from '../components/Basket';
import Brands from '../components/Filters/Brands';
import Sorting from '../components/Filters/Sorting';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="container">
        <div className="left">
          <Sorting />
          <Brands />
        </div>
        <div className="content">
          SA
        </div>
        <div className="right">
          <Basket />
        </div>
      </div>
    </>
  )
}

export default Home
